# Generated by Django 5.0.8 on 2024-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_admin', '0008_alter_subscriptioninfo_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
