# Generated by Django 5.0.8 on 2024-09-24 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestRequest',
            new_name='Dating_InterestRequest',
        ),
        migrations.RenameModel(
            old_name='Shortlist',
            new_name='Dating_Shortlist',
        ),
    ]
