# Generated by Django 5.0.8 on 2024-10-02 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrimonySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('premium', 'Premium (Yearly)')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_limit', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MatrimonySubscription',
                'verbose_name_plural': 'MatrimonySubscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField(blank=True, null=True, unique=True)),
                ('payment_type', models.CharField(choices=[('upi', 'upi'), ('PayPal', 'PayPal'), ('card', 'card'), ('razorpay', 'razorpay')], max_length=50)),
                ('razorpay_order_id', models.CharField(max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=100, null=True)),
                ('razorpay_signature', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_plan', to='dating_subscription.matrimonysubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpayment_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
