# Generated by Django 5.0.8 on 2024-10-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatrimonySubscription',
            new_name='DatingSubscription',
        ),
        migrations.AlterModelOptions(
            name='datingsubscription',
            options={'verbose_name': 'DatingSubscription', 'verbose_name_plural': 'DatingSubscriptions'},
        ),
    ]
