# Generated by Django 5.0.8 on 2024-10-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummys3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dumms3')),
            ],
        ),
    ]
