# Generated by Django 5.0.8 on 2024-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrimonySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('premium', 'Premium (Yearly)')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_limit', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MatrimonySubscription',
                'verbose_name_plural': 'MatrimonySubscriptions',
            },
        ),
    ]
