# Generated by Django 5.0.8 on 2024-09-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U_auth', '0002_shorttermdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortTermDetails',
        ),
    ]
